version: '3.1'
services:
  app:
    build: .
    container_name: online_compiler
    restart: always
    ports:
      - 4600:4600
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: mongodb://mongodb:27017/compiler
    
  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    ports:
      - "27017:27017"